### ISSUE TITLE
Delphi 10 Seattle - won't compile

### ISSUE THREAD

**Issue by Walt1957** [Embarcadero/Delphi4PythonExporter#1]
[dcc32 Error] dclDelphi4PythonExperts.dpk(30): E1030 Invalid compiler directive: 'LIBSUFFIX'

**Comment by lmbelo** [comment]
@Walt1957 the "LIBSUFFIX AUTO" is only available on Delphi 10.4 and greater. Try to remove the following code from the .dpr file:

`{$LIBSUFFIX AUTO}`

https://docwiki.embarcadero.com/RADStudio/Sydney/en/Compiler_directives_for_libraries_or_shared_objects_(Delphi)

**Comment by lmbelo** [comment]
We made the exporter tool backwards compatible to Delphi 10 Seattle. Can you try again, please?

**Comment by lmbelo** [comment]
Closed due to inactivity.
