### ISSUE TITLE
Community Edition Support?

### ISSUE THREAD

**Issue by ShaunRoselt** [Embarcadero/Delphi4PythonExporter#16]
I haven't tried this on `Community Edition` yet as I'm using `Enterprise Edition`, but I have someone that wants to start using the [FMX Library for Python](https://github.com/Embarcadero/DelphiFMX4Python) and I want to recommend installing Community Edition of Delphi. Would they be able to install this plugin in Community Edition and use it normally like any other version of the IDE?

**Comment by lmbelo** [comment]
Yes, it will work on CE. All these projects offer support from Delphi 10.4.2 onwards. The exporter itself might work on early versions too.

**Comment by ShaunRoselt** [comment]
Great, Thanks!

**Comment by lmbelo** [comment]
> Great, Thanks!

Sure thing xP
